### ISSUE TITLE
refreshing mod info renders interface unusable during refresh

### ISSUE THREAD

**Issue by jtac** [Loki-Lokster/2KAN#27]
why lock user out while refreshing the mod list in the background? let the user keep using the interface as the refresh will take longer and longer and longer as time goes by.

**Comment by Loki-Lokster** [comment]
The mod list fetch happens in a separate thread to try and mitigate this. This is one of the reasons we are moving to a C# version to increase the overall responsiveness of the GUI (among many other things).
